name: simple_secure_storage_windows
description: Windows implementation of the Simple Secure Storage plugin.
homepage: https://github.com/Skyost/SimpleSecureStorage
repository: https://github.com/Skyost/SimpleSecureStorage/tree/master/packages/simple_secure_storage_windows
issue_tracker: https://github.com/Skyost/SimpleSecureStorage/issues
version: 0.3.1
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.29.0'

flutter:
  plugin:
    platforms:
      implements: simple_secure_storage
      windows:
        pluginClass: SimpleSecureStorageWindowsPluginCApi

dependencies:
  flutter:
    sdk: flutter
  simple_secure_storage_platform_interface: ^0.2.2
